### ISSUE TITLE
Cannot change configuration ':pattern-examples:providedCompile' after it has been resolved

### ISSUE THREAD

**Issue by progrexor** [Cascading/pattern#4]
Hi,

I'm trying to run the example provided,

```
gradle --info --stacktrace clean build
```

but getting the following error message and unfortunately can't find an answer:

```
Caused by: org.gradle.api.InvalidUserDataException: Cannot change configuration ':pattern-examples:providedCompile' after it has been resolved.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:401)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$400(DefaultConfiguration.java:46)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$VetoContainerChangeAction.run(DefaultConfiguration.java:504)
```

Could you please advice?

Thank you
Andrey

**Comment by fs111** [comment]
That is a gradle 2.x problem. Please use gradle 1.x and it will work.

**Comment by progrexor** [comment]
Thank you. Now it works.

**Comment by ikabar** [comment]
Hi, I encountered the same problem when trying to support Eclipse for an Android project that is developed in Android Studio by following [this tutorial](http://www.nodeclipse.org/projects/gradle/android/aar-for-Eclipse)

I don't think I can use Gradle 1.x due to other gradle issues.

@fs111 Could you explain what is the issue here and maybe suggest a way to solve it in Gradle 2.x

Thanks.

**Comment by fs111** [comment]
hey @ikabar you can use the extra-configurations-plugin in your project (https://github.com/nebula-plugins/gradle-extra-configurations-plugin). It will give you a "provided" configuration, that you know from maven. That is the issue at hand here. We are setting hadoop itself to "provided", so that it does not get packaged and you end up having hard to debug classpath problems.

**Comment by RaviAnnadanam** [comment]
Hi. Here is an alternative solution suggested for this issue.
http://stackoverflow.com/questions/24528371/cascading-java-tutorial-for-the-impatient-part1-gradle-build-fails
